[package]
name = "askama_test"
version = "0.1.0"
authors = ["Steven Anderson <sanderson@sopost.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.10.3"
